Fix failing notebook start when local
BLSQ/openhexa-notebooks pull request #50
Opened 2023-10-20 14:22 UTC by toch

When running locally the JupyterHub, we can't spawn a notebook. In the logs, the container creation returns a 204 HTTP status, i.e. created, but the container can't be found when listing them.

After having checked that the host Docker engine is accessible, it appears that the container was crashing immediatly. We could confirm that by reproducing the running command use to start the container. It was retrieved thanks to @pvanliefland. This command is `/bin/bash -o pipefail -c singleuser`. But the entrypoint of the notebook expects the one of the following command: `notebook`, `singleuser`, `pipeline`, or `help`.

According to the [JupyterHub DockerSpawner document](https://jupyterhub-dockerspawner.readthedocs.io/en/latest/api/index.html#dockerspawner.DockerSpawner.image), it's possible to change the command passed to run a container by setting `c.Spawner.cmd` in the config. That's the fix.

2023-10-20 14:30 UTC, pvanliefland requested changes
@toch thanks for the fix. I think this could work, but `jupyterhub_config.py` is a file used both for local development with `DockerSpawner` and in our cloud environments with `KubeSpawner`.

As we only have an issue in dev / `DockerSpawner`, I suggest we try to apply the same fix in `jupyterhub_dev_config.py` and check if it works.

WDYT?

2023-10-25 14:39 UTC, toch commented
it's already present in the `jupyterhub_dev_config.py` file. So it means, the main one was read not the dev one.

2023-10-26 07:48 UTC, pvanliefland commented
> it's already present in the `jupyterhub_dev_config.py` file. So it means, the main one was read not the dev one.

Sorry but I don't see it in `jupyterhub_dev_config.py`. Where did you spot it?

2023-10-26 08:47 UTC, toch commented
I was tired, it was actually me having added earlier :confused:

It's done and it works (I double checked)

2023-10-26 09:09 UTC, pvanliefland approved these changes
Great, LGTM!

2023-10-26 09:10 UTC, merged